apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repo-app
  template:
    metadata:
      labels:
        app: repo-app
    spec:
      containers:
      - name: app
        image: srshin80/repo-app:latest
        ports:
        - containerPort: 3000
        env:   # 공통 env (없으면 빈 리스트라도 있어야 overlay patch 쉽게 가능)
        - name: ENV
          value: "default"
