apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-

patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml

images:
- name: srshin80/repo-app
  newName: srshin80/repo-app
  newTag: "69"
- name: srshin80/repo-app
  newName: srshin80/repo-app
  newTag: "75"
